version: '3'
services: 
    react-app:
        build: 
            context: .
            dockerfile: Dockerfile.dev 
        ports:
            - "3000:3000"
        volumes: 
            - /home/app/node_modules
            - .:/home/app
        stdin_open: true
    react-test:
        build: 
            context: .
            dockerfile: Dockerfile.dev 
        volumes: 
            - /home/app/node_modules
            - .:/home/app
        command: ["npm", "run", "test"]
        stdin_open: true
    
